// This file is automatically generated.
// Please do not change this file!
export const file: string;
export const line: string;
export const line1: string;
export const line2: string;
export const line3: string;
export const line4: string;
export const line5: string;
export const lineScale: string;
export const lineWrap: string;
export const loader: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const version: string;
