// This file is automatically generated.
// Please do not change this file!
export const carrier: string
export const date: string
export const destination: string
export const file: string
export const info: string
export const logo: string
export const mappings: string
export const names: string
export const origin: string
export const segment: string
export const sourceRoot: string
export const sources: string
export const sourcesContent: string
export const ticket: string
export const time: string
export const version: string
