// This file is automatically generated.
// Please do not change this file!
export const btn: string;
export const btnActive: string;
export const btnDefault: string;
export const file: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const toggle: string;
export const version: string;
