// This file is automatically generated.
// Please do not change this file!
export const btn: string;
export const eur: string;
export const file: string;
export const mappings: string;
export const names: string;
export const price: string;
export const rub: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const usd: string;
export const version: string;
