// This file is automatically generated.
// Please do not change this file!
export const append: string;
export const checkbox: string;
export const face: string;
export const faceChecked: string;
export const file: string;
export const label: string;
export const mappings: string;
export const names: string;
export const sourceRoot: string;
export const sources: string;
export const sourcesContent: string;
export const uncheckOther: string;
export const version: string;
export const wrap: string;
