// This file is automatically generated.
// Please do not change this file!
export const container: string
export const content: string
export const contentWrap: string
export const file: string
export const mappings: string
export const names: string
export const sidebar: string
export const sourceRoot: string
export const sources: string
export const sourcesContent: string
export const version: string
